"""GitHub source for URL discovery."""

import base64
import os
import asyncio

import httpx
import structlog

from app.utils.url_utils import extract_telegram_links

from .base_source import BaseSource

logger = structlog.get_logger()


class GitHubSource(BaseSource):
    """Discovers Telegram links from GitHub repositories."""

    SEARCH_QUERIES = [
        # ==================== BASE QUERIES ====================
        "telegram channel",
        "telegram group",
        "telegram chat",
        "t.me",
        "telegram links",
        "telegram channels list",
        "telegram groups list",
        "best telegram channels",
        "best telegram groups",
        "telegram channels directory",
        "telegram resources",
        "awesome telegram",
        "telegram collections",
        "telegram curated list",
        "telegram awesome list",

        # ==================== RUSSIAN ====================
        "телеграм каналы",
        "телеграм группы",
        "телеграм ссылки",
        "список телеграм каналов",
        "лучшие телеграм каналы",
        "каталог телеграм",

        # ==================== CRYPTO / BLOCKCHAIN ====================
        "telegram crypto",
        "telegram bitcoin",
        "telegram ethereum",
        "telegram defi",
        "telegram nft",
        "telegram blockchain",
        "telegram web3",
        "telegram trading",
        "telegram stocks",
        "telegram forex",
        "telegram investing",
        "crypto telegram channels",
        "bitcoin telegram group",
        "ethereum telegram group",
        "defi telegram group",
        "nft telegram channel",
        "trading telegram group",
        "blockchain telegram channel",
        "web3 telegram group",
        "crypto signals telegram",
        "trading signals telegram",
        "best crypto telegram",
        "crypto alerts telegram",
        "defi alerts telegram",
        "nft drops telegram",
        "solana telegram group",
        "polygon telegram group",
        "avalanche telegram group",
        "cardano telegram group",
        "polkadot telegram group",
        "chainlink telegram group",
        "uniswap telegram group",
        "aave telegram group",
        "compound telegram group",
        "metamask telegram group",
        "phantom wallet telegram",
        "trust wallet telegram",
        "ledger telegram group",
        "trezor telegram group",
        "coinbase telegram group",
        "binance telegram group",
        "kraken telegram group",
        "bybit telegram group",
        "okx telegram group",
        "huobi telegram group",
        "gate.io telegram group",
        "whale alert telegram",
        "crypto news telegram",
        "bitcoin news telegram",
        "ethereum news telegram",
        "crypto analysis telegram",
        "bitcoin analysis telegram",
        "technical analysis telegram",
        "crypto education telegram",
        "bitcoin education telegram",
        "learn crypto telegram",

        # ==================== TECH / PROGRAMMING ====================
        "telegram python",
        "telegram javascript",
        "telegram golang",
        "telegram rust",
        "telegram java",
        "telegram programming",
        "telegram coding",
        "telegram developer",
        "telegram devops",
        "telegram backend",
        "telegram frontend",
        "telegram ai",
        "telegram machine learning",
        "telegram data science",
        "python telegram channel",
        "javascript telegram group",
        "programming telegram group",
        "coding telegram group",
        "developer telegram channel",
        "devops telegram channel",
        "backend telegram group",
        "frontend telegram group",
        "ai telegram channel",
        "machine learning telegram group",
        "data science telegram group",
        "tech telegram channel",
        "technology telegram group",
        "it telegram channel",
        "coding telegram channel",
        "developer telegram group",
        "python telegram group",
        "javascript telegram channel",
        "golang telegram group",
        "rust telegram group",
        "java telegram group",
        "c++ telegram group",
        "php telegram group",
        "ruby telegram group",
        "swift telegram group",
        "kotlin telegram group",
        "typescript telegram group",
        "react telegram group",
        "vue telegram group",
        "angular telegram group",
        "nodejs telegram group",
        "django telegram group",
        "flask telegram group",
        "fastapi telegram group",
        "spring telegram group",
        "laravel telegram group",
        "rails telegram group",
        "flutter telegram group",
        "react native telegram group",
        "ios development telegram",
        "android development telegram",
        "web development telegram",
        "mobile development telegram",
        "game development telegram",
        "unity telegram group",
        "unreal engine telegram group",
        "godot telegram group",
        "blender telegram group",
        "3d modeling telegram",
        "animation telegram group",
        "vfx telegram group",
        "motion graphics telegram",
        "graphic design telegram",
        "ui ux telegram group",
        "figma telegram group",
        "sketch telegram group",
        "adobe telegram group",
        "photoshop telegram group",
        "illustrator telegram group",
        "premiere telegram group",
        "after effects telegram group",
        "cinema 4d telegram group",
        "houdini telegram group",
        "maya telegram group",
        "zbrush telegram group",
        "substance painter telegram",
        "sound design telegram",
        "music production telegram",
        "audio engineering telegram",
        "daw telegram group",
        "ableton telegram group",
        "fl studio telegram group",
        "logic pro telegram group",
        "guitar telegram group",
        "piano telegram group",
        "drums telegram group",
        "vocal telegram group",
        "dj telegram group",
        "edm telegram group",
        "techno telegram group",
        "house telegram group",
        "ambient telegram group",
        "drum and bass telegram",
        "dubstep telegram group",
        "trance telegram group",
        "rock telegram group",
        "metal telegram group",
        "jazz telegram group",
        "blues telegram group",
        "hip hop telegram group",
        "rap telegram group",
        "indie telegram group",
        "music business telegram",
        "music industry telegram",
        "music marketing telegram",
        "spotify telegram group",
        "soundcloud telegram group",
        "bandcamp telegram group",
        "youtube music telegram",
        "music blog telegram",
        "music review telegram",
        "music podcast telegram",
        "music festival telegram",
        "concert telegram group",
        "music gear telegram",
        "guitar gear telegram",
        "pedal telegram group",
        "amp telegram group",
        "synth telegram group",
        "drum machine telegram",
        "midi telegram group",

        # ==================== GAMING ====================
        "telegram gaming",
        "telegram games",
        "telegram esport",
        "telegram steam",
        "telegram playstation",
        "telegram xbox",
        "telegram nintendo",
        "gaming telegram channel",
        "gaming telegram group",
        "games telegram group",
        "esport telegram group",
        "steam telegram group",
        "playstation telegram group",
        "xbox telegram group",
        "nintendo telegram group",
        "pc gaming telegram",
        "mobile gaming telegram",
        "console gaming telegram",
        "vr gaming telegram",
        "gaming news telegram",
        "gaming community telegram",
        "game reviews telegram",
        "game deals telegram",
        "esports news telegram",
        "esports betting telegram",
        "cs2 telegram group",
        "valorant telegram group",
        "league of legends telegram",
        "dota 2 telegram group",
        "fortnite telegram group",
        "apex legends telegram",
        "pubg telegram group",
        "call of duty telegram",
        "gta telegram group",
        "minecraft telegram group",
        "roblox telegram group",
        "elden ring telegram group",
        "dark souls telegram group",
        "cyberpunk telegram group",
        "gaming memes telegram",
        "gaming clips telegram",
        "gaming streams telegram",
        "twitch telegram group",
        "youtube gaming telegram",
        "game dev telegram group",
        "indie game telegram",
        "roguelike telegram group",
        "rpg telegram group",
        "mmorpg telegram group",
        "fps telegram group",
        "strategy telegram group",
        "rts telegram group",
        "moba telegram group",
        "battle royale telegram",
        "survival telegram group",
        "horror game telegram",
        "puzzle game telegram",
        "racing game telegram",
        "simulation telegram group",
        "sandbox telegram group",
        "open world telegram",
        "visual novel telegram",
        "fighting game telegram",
        "board game telegram",
        "card game telegram",
        "tabletop telegram group",
        "dnd telegram group",
        "warhammer telegram group",
        "magic the gathering telegram",
        "game design telegram group",
        "game art telegram group",
        "game audio telegram group",
        "game programming telegram",
        "game engine telegram",
        "unity telegram channel",
        "unreal telegram channel",
        "godot telegram channel",
        "game jams telegram",
        "indie dev telegram group",
        "game industry telegram",

        # ==================== NEWS / MEDIA ====================
        "telegram news",
        "telegram media",
        "telegram press",
        "news telegram channel",
        "news telegram group",
        "media telegram channel",
        "breaking news telegram",
        "world news telegram",
        "tech news telegram",
        "crypto news telegram",
        "business news telegram",
        "sports news telegram",
        "entertainment news telegram",
        "science news telegram",
        "health news telegram",
        "political news telegram",
        "financial news telegram",
        "alternative news telegram",
        "independent media telegram",
        "citizen journalism telegram",
        "news aggregator telegram",
        "news digest telegram",
        "daily news telegram",
        "news alerts telegram",
        "news bot telegram",
        "best news telegram",
        "trusted news telegram",
        "fact check telegram group",
        "media literacy telegram",
        "journalism telegram group",
        "press freedom telegram",
        "investigative journalism telegram",

        # ==================== BUSINESS / STARTUP ====================
        "telegram business",
        "telegram startup",
        "telegram marketing",
        "telegram seo",
        "business telegram channel",
        "business telegram group",
        "startup telegram group",
        "marketing telegram group",
        "seo telegram group",
        "entrepreneurship telegram",
        "founder telegram group",
        "vc telegram group",
        "fundraising telegram group",
        "investor telegram group",
        "lean startup telegram",
        "mvp telegram group",
        "growth hacking telegram",
        "saas telegram group",
        "ecommerce telegram group",
        "dropshipping telegram group",
        "affiliate marketing telegram",
        "social media marketing telegram",
        "content marketing telegram",
        "email marketing telegram",
        "ppc telegram group",
        "google ads telegram group",
        "facebook ads telegram group",
        "instagram marketing telegram",
        "tiktok marketing telegram",
        "youtube marketing telegram",
        "linkedin marketing telegram",
        "influencer marketing telegram",
        "brand building telegram",
        "personal branding telegram",
        "copywriting telegram group",
        "blogging telegram group",
        "podcasting telegram group",
        "newsletter telegram group",
        "community building telegram",
        "networking telegram group",
        "freelancing telegram group",
        "agency telegram group",
        "remote work telegram group",
        "digital nomad telegram",
        "productivity telegram group",
        "project management telegram",
        "agile telegram group",
        "scrum telegram group",
        "leadership telegram group",
        "management telegram group",
        "hiring telegram group",
        "recruiting telegram group",
        "business strategy telegram",
        "business plan telegram",
        "customer acquisition telegram",
        "monetization telegram group",
        "revenue telegram group",
        "profit telegram group",
        "business model telegram",
        "b2b telegram group",
        "b2c telegram group",
        "content creation telegram",
        "community management telegram",

        # ==================== EDUCATION ====================
        "telegram education",
        "telegram learning",
        "telegram course",
        "telegram tutorial",
        "education telegram channel",
        "education telegram group",
        "learning telegram group",
        "course telegram group",
        "tutorial telegram group",
        "online course telegram",
        "mooc telegram group",
        "e-learning telegram group",
        "self study telegram group",
        "study group telegram",
        "homework help telegram",
        "tutoring telegram group",
        "academic telegram group",
        "university telegram group",
        "college telegram group",
        "coding bootcamp telegram",
        "language learning telegram",
        "english learning telegram",
        "spanish learning telegram",
        "french learning telegram",
        "german learning telegram",
        "chinese learning telegram",
        "japanese learning telegram",
        "korean learning telegram",
        "toefl telegram group",
        "ielts telegram group",
        "gre telegram group",
        "math telegram group",
        "physics telegram group",
        "chemistry telegram group",
        "biology telegram group",
        "science telegram group",
        "engineering telegram group",
        "computer science telegram",
        "data science telegram",
        "statistics telegram group",
        "economics telegram group",
        "psychology telegram group",
        "philosophy telegram group",
        "history telegram group",
        "literature telegram group",
        "writing telegram group",
        "creative writing telegram",
        "critical thinking telegram",
        "study skills telegram",
        "memory techniques telegram",
        "speed reading telegram",
        "growth mindset telegram",
        "motivation telegram group",
        "discipline telegram group",
        "habits telegram group",
        "goals telegram group",
        "time management telegram",
        "organization telegram group",
        "focus telegram group",
        "procrastination telegram group",
        "stem education telegram",
        "arts education telegram",
        "financial literacy telegram",
        "digital literacy telegram",
        "media literacy telegram",
        "inclusive education telegram",
        "special education telegram",
        "homeschooling telegram group",
        "montessori telegram group",
        "waldorf telegram group",

        # ==================== HEALTH / FITNESS ====================
        "telegram health",
        "telegram fitness",
        "telegram workout",
        "telegram gym",
        "telegram yoga",
        "telegram meditation",
        "health telegram channel",
        "health telegram group",
        "fitness telegram group",
        "workout telegram group",
        "gym telegram group",
        "yoga telegram group",
        "meditation telegram group",
        "wellness telegram group",
        "mental health telegram",
        "physical health telegram",
        "holistic health telegram",
        "alternative medicine telegram",
        "natural remedies telegram",
        "herbal medicine telegram",
        "physical therapy telegram",
        "psychotherapy telegram group",
        "counseling telegram group",
        "therapy telegram group",
        "cbt telegram group",
        "addiction therapy telegram",
        "recovery telegram group",
        "sobriety telegram group",
        "stress management telegram",
        "anxiety management telegram",
        "depression management telegram",
        "anger management telegram",
        "grief counseling telegram",
        "trauma recovery telegram",
        "ptsd telegram group",
        "eating disorders telegram",
        "body image telegram",
        "self-harm telegram group",
        "suicide prevention telegram",
        "crisis intervention telegram",
        "domestic violence telegram",
        "bullying telegram group",
        "harassment telegram group",
        "discrimination telegram group",
        "self-care telegram group",
        "mindfulness telegram group",
        "breathwork telegram group",
        "tai chi telegram group",
        "reiki telegram group",
        "energy healing telegram",
        "crystal healing telegram",
        "sound healing telegram",
        "aromatherapy telegram group",
        "massage telegram group",
        "reflexology telegram group",
        "flexibility telegram group",
        "stretching telegram group",
        "breathing exercises telegram",
        "yoga nidra telegram",
        "guided meditation telegram",
        "zen meditation telegram",
        "vipassana meditation telegram",
        "transcendental meditation telegram",
        "loving kindness meditation telegram",
        "mindfulness based stress reduction telegram",
        "acceptance and commitment therapy telegram",
        "dialectical behavior therapy telegram",
        "cognitive behavioral therapy telegram",
        "positive psychology telegram",
        "flourishing telegram group",
        "wellbeing science telegram",
        "happiness research telegram",
        "life satisfaction telegram",

        # ==================== FOOD / COOKING ====================
        "telegram food",
        "telegram cooking",
        "telegram recipe",
        "telegram restaurant",
        "food telegram channel",
        "food telegram group",
        "cooking telegram group",
        "recipe telegram group",
        "restaurant telegram group",
        "vegan telegram group",
        "vegetarian telegram group",
        "keto telegram group",
        "paleo telegram group",
        "plant based telegram",
        "gluten free telegram group",
        "low carb telegram group",
        "meal prep telegram group",
        "slow cooker telegram group",
        "instant pot telegram group",
        "air fryer telegram group",
        "sous vide telegram group",
        "smoker telegram group",
        "grill telegram group",
        "bbq telegram group",
        "baking telegram group",
        "bread baking telegram",
        "pastry telegram group",
        "cake decorating telegram",
        "pizza telegram group",
        "pasta telegram group",
        "sushi telegram group",
        "ramen telegram group",
        "chinese food telegram",
        "japanese food telegram",
        "korean food telegram",
        "thai food telegram",
        "indian food telegram",
        "mexican food telegram",
        "italian food telegram",
        "french food telegram",
        "street food telegram",
        "food truck telegram",
        "food festival telegram",
        "food blog telegram",
        "food photography telegram",
        "food science telegram",
        "food safety telegram",
        "organic food telegram",
        "local food telegram",
        "farm to table telegram",
        "home gardening telegram",
        "hydroponics telegram group",
        "permaculture telegram group",
        "food waste telegram group",
        "food preservation telegram",
        "fermenting telegram group",
        "pickling telegram group",
        "cheese making telegram",
        "wine making telegram",
        "beer brewing telegram",
        "cocktail making telegram",
        "coffee roasting telegram",
        "tea telegram group",
        "supplement telegram group",
        "vitamin telegram group",
        "nootropic telegram group",
        "adaptogen telegram group",
        "fasting telegram group",
        "intermittent fasting telegram",
        "ketogenic diet telegram",
        "high protein telegram group",
        "amino acid telegram group",
        "muscle recovery telegram",
        "muscle growth telegram",
        "strength training telegram",
        "powerlifting telegram group",
        "bodybuilding telegram group",
        "crossfit telegram group",
        "calisthenics telegram group",
        "home workout telegram group",
        "gym workout telegram group",
        "outdoor workout telegram group",
        "beginner workout telegram",
        "senior workout telegram group",
        "injury prevention telegram",
        "overtraining telegram group",
        "deload telegram group",
        "rest day telegram group",
        "active recovery telegram",
        "sleep recovery telegram",
        "nutrition recovery telegram",
        "hydration telegram group",
        "post workout nutrition telegram",
        "pre workout nutrition telegram",
        "meal timing telegram",
        "weight loss telegram group",
        "weight gain telegram group",
        "body recomposition telegram",
        "fat loss telegram group",
        "muscle gain telegram group",
        "maintenance calories telegram",
        "caloric deficit telegram",
        "metabolism telegram group",
        "metabolic flexibility telegram",
        "ketosis telegram group",
        "fat adaptation telegram",
        "vo2 max telegram group",
        "lactate threshold telegram",
        "heart rate zones telegram",
        "blood pressure telegram group",
        "cholesterol telegram group",
        "blood sugar telegram group",
        "insulin sensitivity telegram",
        "cortisol telegram group",
        "testosterone telegram group",
        "growth hormone telegram",
        "immune function telegram",
        "inflammatory markers telegram",
        "antioxidant telegram group",
        "anti-inflammatory telegram",
        "vitamin c telegram group",
        "vitamin d telegram group",
        "magnesium telegram group",
        "zinc telegram group",
        "omega-3 telegram group",

        # ==================== TRAVEL ====================
        "telegram travel",
        "telegram tourism",
        "telegram vacation",
        "travel telegram channel",
        "travel telegram group",
        "tourism telegram group",
        "vacation telegram group",
        "backpacking telegram group",
        "digital nomad telegram",
        "solo travel telegram group",
        "budget travel telegram",
        "luxury travel telegram",
        "family travel telegram",
        "road trip telegram group",
        "camping telegram group",
        "hiking telegram group",
        "diving telegram group",
        "surfing telegram group",
        "skiing telegram group",
        "sailing telegram group",
        "cruising telegram group",
        "fishing telegram group",
        "safari telegram group",
        "wildlife telegram group",
        "national parks telegram",
        "cultural tourism telegram",
        "eco tourism telegram",
        "adventure tourism telegram",
        "food tourism telegram",
        "wine tourism telegram",
        "festival tourism telegram",
        "beach telegram group",
        "island telegram group",
        "mountain telegram group",
        "desert telegram group",
        "tropical telegram group",
        "mediterranean telegram",
        "southeast asia telegram",
        "east africa telegram",
        "south america telegram",
        "central america telegram",
        "eastern europe telegram",
        "western europe telegram",
        "east asia telegram",
        "middle east telegram group",
        "pacific islands telegram",
        "australia telegram group",
        "new zealand telegram group",
        "japan travel telegram",
        "thailand travel telegram",
        "indonesia travel telegram",
        "india travel telegram",
        "nepal travel telegram",
        "iceland travel telegram",
        "norway travel telegram",
        "greece travel telegram",
        "turkey travel telegram",
        "morocco travel telegram",
        "egypt travel telegram",
        "south africa telegram",
        "kenya telegram group",
        "tanzania telegram group",
        "colombia travel telegram",
        "peru travel telegram",
        "costa rica telegram",

        # ==================== ART / DESIGN ====================
        "telegram art",
        "telegram design",
        "telegram photo",
        "art telegram channel",
        "art telegram group",
        "design telegram group",
        "photo telegram group",
        "photography telegram group",
        "illustration telegram group",
        "digital art telegram group",
        "traditional art telegram",
        "fine art telegram group",
        "contemporary art telegram",
        "abstract art telegram group",
        "street art telegram group",
        "graffiti telegram group",
        "mural telegram group",
        "tattoo art telegram",
        "logo design telegram",
        "brand design telegram",
        "graphic design telegram",
        "print design telegram",
        "packaging design telegram",
        "web design telegram",
        "ui design telegram group",
        "ux design telegram group",
        "figma telegram group",
        "sketch telegram group",
        "adobe telegram group",
        "3d design telegram",
        "blender telegram group",
        "cinema 4d telegram group",
        "motion design telegram",
        "animation telegram group",
        "video production telegram",
        "photography telegram group",
        "portrait photography telegram",
        "landscape photography telegram",
        "street photography telegram",
        "wedding photography telegram",
        "product photography telegram",
        "food photography telegram",
        "drone photography telegram",
        "film photography telegram",
        "photo editing telegram group",
        "photo retouching telegram group",
        "lightroom telegram group",
        "photoshop telegram group",
        "color theory telegram",
        "typography telegram group",
        "layout telegram group",
        "branding telegram group",
        "identity design telegram",
        "visual identity telegram",
        "design systems telegram group",
        "component libraries telegram",
        "style guides telegram group",
        "accessibility telegram group",
        "inclusive design telegram",
        "universal design telegram",
        "responsive design telegram",
        "mobile first telegram",
        "prototyping telegram group",
        "user research telegram",
        "usability testing telegram",
        "wireframing telegram group",
        "information architecture telegram",
        "interaction design telegram",
        "motion design telegram",

        # ==================== SCIENCE ====================
        "telegram science",
        "telegram physics",
        "telegram chemistry",
        "telegram biology",
        "telegram astronomy",
        "science telegram channel",
        "science telegram group",
        "physics telegram group",
        "chemistry telegram group",
        "biology telegram group",
        "astronomy telegram group",
        "space science telegram",
        "earth science telegram",
        "environmental science telegram",
        "geology telegram group",
        "meteorology telegram group",
        "ecology telegram group",
        "evolution telegram group",
        "genetics telegram group",
        "microbiology telegram",
        "neuroscience telegram group",
        "cognitive science telegram",
        "mathematics telegram group",
        "algebra telegram group",
        "geometry telegram group",
        "calculus telegram group",
        "statistics telegram group",
        "computer science telegram",
        "quantum physics telegram",
        "relativity telegram group",
        "thermodynamics telegram",
        "particle physics telegram",
        "astrophysics telegram",
        "cosmology telegram group",
        "dark matter telegram group",
        "black holes telegram group",
        "big bang telegram group",
        "nuclear physics telegram",
        "biotechnology telegram",
        "nanotechnology telegram",
        "materials science telegram",
        "quantum computing telegram",
        "artificial intelligence telegram",
        "machine learning telegram",
        "deep learning telegram",
        "data science telegram",
        "complexity theory telegram",
        "chaos theory telegram",
        "game theory telegram",
        "information theory telegram",
        "fusion energy telegram",
        "solar energy telegram",
        "wind energy telegram group",
        "battery technology telegram",
        "graphene telegram group",
        "carbon nanotubes telegram",
        "superconductivity telegram",
        "plasma physics telegram",
        "semiconductor physics telegram",
        "quantum dots telegram group",
        "metamaterials telegram group",
        "biomaterials telegram group",

        # ==================== CARS / AUTOMOTIVE ====================
        "telegram cars",
        "telegram auto",
        "telegram motorsport",
        "cars telegram channel",
        "cars telegram group",
        "auto telegram group",
        "motorsport telegram group",
        "supercars telegram group",
        "classic cars telegram",
        "electric cars telegram",
        "hybrid cars telegram",
        "motorcycle telegram group",
        "car tuning telegram",
        "car modification telegram",
        "car detailing telegram",
        "car care telegram group",
        "car parts telegram group",
        "car maintenance telegram",
        "car repair telegram group",
        "diy car repair telegram",
        "car insurance telegram",
        "car finance telegram group",
        "car buying telegram group",
        "car review telegram group",
        "car news telegram group",
        "car photography telegram",
        "car meet telegram group",
        "car show telegram group",
        "f1 telegram group",
        "formula 1 telegram group",
        "motogp telegram group",
        "nascar telegram group",
        "rally telegram group",
        "drift telegram group",
        "drag racing telegram group",
        "endurance racing telegram",
        "gt racing telegram group",
        "autonomous driving telegram",
        "self-driving cars telegram",
        "connected cars telegram group",
        "ev charging telegram group",
        "ev battery telegram group",
        "tesla telegram group",
        "lucid telegram group",
        "rivian telegram group",
        "nio telegram group",
        "byd telegram group",
        "electric car reviews telegram",
        "electric car news telegram",
        "electric car comparison telegram",
        "electric car range telegram",
        "electric car charging telegram",
        "ev infrastructure telegram",

        # ==================== JOBS / FREELANCE ====================
        "telegram jobs",
        "telegram freelance",
        "telegram remote work",
        "telegram hiring",
        "jobs telegram channel",
        "jobs telegram group",
        "freelance telegram group",
        "remote work telegram group",
        "hiring telegram group",
        "remote jobs telegram",
        "work from home telegram",
        "digital nomad telegram group",
        "freelancing telegram group",
        "upwork telegram group",
        "fiverr telegram group",
        "toptal telegram group",
        "linkedin jobs telegram",
        "indeed telegram group",
        "glassdoor telegram group",
        "remote.co telegram",
        "weworkremotely telegram",
        "remotive telegram group",
        "coworking telegram group",
        "freelance tips telegram",
        "freelance business telegram",
        "freelance taxes telegram",
        "freelance invoicing telegram",
        "freelance contracts telegram",
        "freelance clients telegram",
        "freelance pricing telegram",
        "freelance portfolio telegram",
        "freelance marketing telegram",
        "freelance productivity telegram",
        "freelance community telegram",
        "freelance networking telegram",

        # ==================== BOOKS / LITERATURE ====================
        "telegram books",
        "telegram reading",
        "telegram literature",
        "telegram audiobooks",
        "telegram kindle",
        "books telegram channel",
        "books telegram group",
        "reading telegram group",
        "literature telegram group",
        "audiobooks telegram group",
        "book club telegram group",
        "book review telegram group",
        "book recommendation telegram",
        "book discussion telegram group",
        "book exchange telegram group",
        "book sale telegram group",
        "book free telegram group",
        "book download telegram group",
        "book pdf telegram group",
        "book epub telegram group",
        "book community telegram group",
        "book collector telegram group",
        "book publishing telegram group",
        "book self-publishing telegram",
        "book fiction telegram group",
        "book nonfiction telegram group",
        "book mystery telegram group",
        "book thriller telegram group",
        "book fantasy telegram group",
        "book science fiction telegram",
        "book romance telegram group",
        "book young adult telegram",
        "book children telegram group",
        "book graphic novel telegram",
        "book manga telegram group",
        "book poetry telegram group",
        "book memoir telegram group",
        "book biography telegram group",
        "book history telegram group",
        "book science telegram group",
        "book philosophy telegram group",
        "book psychology telegram group",
        "book self-help telegram group",
        "book business telegram group",
        "book finance telegram group",
        "book investing telegram group",
        "book entrepreneurship telegram",
        "book leadership telegram group",
        "book productivity telegram group",
        "book spirituality telegram group",
        "book health telegram group",
        "book cooking telegram group",
        "book travel telegram group",
        "book art telegram group",
        "book music telegram group",
        "book photography telegram",
        "book programming telegram group",
        "book computer science telegram",
        "book technology telegram group",

        # ==================== PHOTOGRAPHY ====================
        "telegram photography",
        "telegram camera",
        "telegram drone",
        "telegram video",
        "photography telegram channel",
        "photography telegram group",
        "camera telegram group",
        "drone telegram group",
        "video telegram group",
        "portrait photography telegram",
        "landscape photography telegram",
        "street photography telegram",
        "documentary photography telegram",
        "wedding photography telegram",
        "event photography telegram",
        "product photography telegram",
        "food photography telegram",
        "fashion photography telegram",
        "architecture photography telegram",
        "nature photography telegram",
        "wildlife photography telegram",
        "macro photography telegram",
        "astro photography telegram",
        "underwater photography telegram",
        "aerial photography telegram",
        "drone photography telegram",
        "smartphone photography telegram",
        "film photography telegram",
        "digital photography telegram",
        "black and white photography telegram",
        "long exposure photography telegram",
        "time lapse photography telegram",
        "panoramic photography telegram",
        "hdr photography telegram group",
        "raw photography telegram group",
        "photo editing telegram group",
        "photo retouching telegram group",
        "photo manipulation telegram",
        "photo restoration telegram",
        "photo enhancement telegram",
        "photo filter telegram group",
        "photo preset telegram group",
        "photo lightroom telegram group",
        "photo photoshop telegram group",
        "photo portfolio telegram group",
        "photo gallery telegram group",
        "photo exhibition telegram",
        "photo contest telegram group",
        "photo workshop telegram group",
        "photo course telegram group",
        "photo tutorial telegram group",
        "photo tip telegram group",
        "photo composition telegram",
        "photo lighting telegram group",
        "photo exposure telegram group",
        "photo focus telegram group",
        "photo depth of field telegram",
        "photo bokeh telegram group",
        "photo lens telegram group",
        "photo camera body telegram",
        "photo tripod telegram group",
        "photo flash telegram group",
        "photo studio telegram group",
        "photo business telegram group",
        "photo marketing telegram group",
        "photo seo telegram group",
        "photo workflow telegram group",
        "photo batch processing telegram",
        "photo tethered shooting telegram",
        "photo hdr bracketing telegram",
        "photo focus stacking telegram",
        "photo panorama stitching telegram",
        "photo color correction telegram",
        "photo color grading telegram",
        "photo skin retouching telegram",
        "photo portrait retouching telegram",
        "photo product retouching telegram",
        "photo real estate photography telegram",
        "photo aerial survey telegram",
        "photo photogrammetry telegram",
        "photo lidar telegram group",
        "photo point cloud telegram group",
        "photo 3d scanning telegram group",
        "photo volumetric capture telegram",
        "photo light field telegram group",
        "photo computational imaging telegram",

        # ==================== ADDITIONAL TECHNICAL ====================
        "telegram docker",
        "telegram kubernetes",
        "telegram aws",
        "telegram azure",
        "telegram gcp",
        "docker telegram group",
        "kubernetes telegram group",
        "aws telegram group",
        "azure telegram group",
        "gcp telegram group",
        "terraform telegram group",
        "ansible telegram group",
        "ci cd telegram group",
        "github actions telegram",
        "gitlab ci telegram",
        "jenkins telegram group",
        "prometheus telegram group",
        "grafana telegram group",
        "elk stack telegram group",
        "redis telegram group",
        "postgresql telegram group",
        "mongodb telegram group",
        "elasticsearch telegram group",
        "kafka telegram group",
        "rabbitmq telegram group",
        "graphql telegram group",
        "rest api telegram group",
        "grpc telegram group",
        "websocket telegram group",
        "microservices telegram group",
        "monolith telegram group",
        "serverless telegram group",
        "lambda telegram group",
        "cloud functions telegram",
        "edge computing telegram group",
        "iot telegram group",
        "blockchain telegram group",
        "smart contracts telegram",
        "solidity telegram group",
        "web3 telegram group",
        "metaverse telegram group",
        "vr telegram group",
        "ar telegram group",
        "xr telegram group",
        "quantum computing telegram",
        "machine learning telegram",
        "deep learning telegram",
        "nlp telegram group",
        "computer vision telegram",
        "reinforcement learning telegram",
        "transformer telegram group",
        "llm telegram group",
        "gpt telegram group",
        "bert telegram group",
        "fine tuning telegram group",
        "prompt engineering telegram",
        "rag telegram group",
        "vector database telegram",
        "embeddings telegram group",
        "mlops telegram group",
        "data pipeline telegram",
        "etl telegram group",
        "data warehouse telegram",
        "data lake telegram group",
        "streaming telegram group",
        "batch processing telegram",
        "real time processing telegram",
        "cybersecurity telegram group",
        "penetration testing telegram",
        "bug bounty telegram group",
        "ctf telegram group",
        "hacking telegram group",
        "infosec telegram group",
        "privacy telegram group",
        "encryption telegram group",
        "vpn telegram group",
        "linux telegram group",
        "ubuntu telegram group",
        "arch telegram group",
        "fedora telegram group",
        "windows telegram group",
        "macos telegram group",
        "android telegram group",
        "ios telegram group",
        "react telegram group",
        "vue telegram group",
        "angular telegram group",
        "svelte telegram group",
        "nextjs telegram group",
        "nuxt telegram group",
        "nodejs telegram group",
        "deno telegram group",
        "bun telegram group",
        "django telegram group",
        "flask telegram group",
        "fastapi telegram group",
        "express telegram group",
        "nestjs telegram group",
        "rails telegram group",
        "laravel telegram group",
        "spring telegram group",
        "dotnet telegram group",
        "flutter telegram group",
        "react native telegram group",
        "swift telegram group",
        "kotlin telegram group",
        "rust telegram group",
        "go telegram group",
        "zig telegram group",
        "carbon telegram group",
        "mojo telegram group",
        "v language telegram",
        "nim telegram group",
        "crystal telegram group",
        "elixir telegram group",
        "erlang telegram group",
        "clojure telegram group",
        "haskell telegram group",
        "ocaml telegram group",
        "fsharp telegram group",
        "scala telegram group",
        "kotlin telegram group",
        "typescript telegram group",
        "coffeeScript telegram group",
        "elm telegram group",
        "purescript telegram group",
        "reasonml telegram group",
        "gleam telegram group",
        "red language telegram",
        "raku telegram group",
        "lua telegram group",
        "r telegram group",
        "julia telegram group",
        "matlab telegram group",
        "mathematica telegram group",
        "maple telegram group",
        "excel telegram group",
        "google sheets telegram",
        "powershell telegram group",
        "bash telegram group",
        "zsh telegram group",
        "fish telegram group",
        "nushell telegram group",
        "oil shell telegram",
        "starship telegram group",
        "oh my zsh telegram",
        "tmux telegram group",
        "neovim telegram group",
        "vim telegram group",
        "emacs telegram group",
        "vscode telegram group",
        "intellij telegram group",
        "pycharm telegram group",
        "webstorm telegram group",
        "android studio telegram",
        "xcode telegram group",
        "sublime text telegram",
        "atom telegram group",
        "notepad++ telegram",
        "nano telegram group",
        "helix telegram group",
        "kakoune telegram group",
        "lite xl telegram group",
        "zedit telegram group",
        "amp telegram group",
        "sublime merge telegram",
        "gitkraken telegram group",
        "sourcetree telegram group",
        "tower telegram group",
        "lazygit telegram group",
        "tig telegram group",
        "github desktop telegram",
        "fork git client telegram",
        "smartgit telegram group",
        "perforce telegram group",
        "mercurial telegram group",
        "svn telegram group",
        "bazaar telegram group",
        "fossil telegram group",
        "darcs telegram group",
        "pijul telegram group",
        "jujutsu telegram group",
        "nix telegram group",
        "guix telegram group",
        "homebrew telegram group",
        "chocolatey telegram group",
        "scoop telegram group",
        "winget telegram group",
        "apt telegram group",
        "dnf telegram group",
        "pacman telegram group",
        "brew telegram group",
        "portage telegram group",
        "slapt-get telegram group",
        "xbps telegram group",
        "apk telegram group",
        "pkg telegram group",
        "snap telegram group",
        "flatpak telegram group",
        "appimage telegram group",
        "docker telegram group",
        "podman telegram group",
        "containerd telegram group",
        "cri-o telegram group",
        "lxd telegram group",
        "lxc telegram group",
        "systemd-nspawn telegram",
        "firejail telegram group",
        "bubblewrap telegram group",
        "gvisor telegram group",
        "kata containers telegram",
        "microvm telegram group",
        "firecracker telegram group",
        "cloud hypervisor telegram",
        "qemu telegram group",
        "kvm telegram group",
        "xen telegram group",
        "vmware telegram group",
        "virtualbox telegram group",
        "hyper-v telegram group",
        "proxmox telegram group",
        "esxi telegram group",
        "bhyve telegram group",
        "openvz telegram group",
        "lxc telegram group",
        "docker compose telegram",
        "docker swarm telegram",
        "k3s telegram group",
        "k0s telegram group",
        "microk8s telegram group",
        "rancher telegram group",
        "openshift telegram group",
        "eks telegram group",
        "aks telegram group",
        "gke telegram group",
        "linode kubernetes telegram",
        "digitalocean kubernetes telegram",
        "vultr kubernetes telegram",
        "hetzner kubernetes telegram",
        "ovh kubernetes telegram",
        "scaleway kubernetes telegram",
        "civo kubernetes telegram",
        "kubeflow telegram group",
        "argoflow telegram group",
        "tekton telegram group",
        "flux telegram group",
        "fluxcd telegram group",
        "argocd telegram group",
        "flux2 telegram group",
        "helm telegram group",
        "kustomize telegram group",
        "skaffold telegram group",
        "tilt telegram group",
        "devspace telegram group",
        "garden telegram group",
        "telepresence telegram group",
        "linkerd telegram group",
        "istio telegram group",
        "envoy telegram group",
        "consul telegram group",
        "vault telegram group",
        "nomad telegram group",
        "packer telegram group",
        "vagrant telegram group",
        "puppet telegram group",
        "chef telegram group",
        "salt telegram group",
        "foreman telegram group",
        "cobbler telegram group",
        "MAAS telegram group",
        "juju telegram group",
        "ansible telegram group",
        "fabric telegram group",
        "saltstack telegram group",
        "powershell dsc telegram",
        "bicep telegram group",
        "cdktf telegram group",
        "crossplane telegram group",
        "pulumi telegram group",
        "cdk telegram group",
        "cloud formation telegram",
        "arm templates telegram",
        "deployment manager telegram",
        "terraform cloud telegram",
        "env0 telegram group",
        "spacelift telegram group",
        "scalr telegram group",
        "firefly telegram group",
        "infracost telegram group",
        "checkov telegram group",
        "tfsec telegram group",
        "tflint telegram group",
        "terragrunt telegram group",
        "terramate telegram group",
        "atmos telegram group",
        "stackguardian telegram group",
        "mindera terraform telegram",
        "bridgecrew telegram group",
        "prisma cloud telegram",
        "snyk infrastructure telegram",
        "trivy telegram group",
        "grype telegram group",
        "syft telegram group",
        "cosign telegram group",
        "notary telegram group",
        "sigstore telegram group",
        "kyverno telegram group",
        "opa telegram group",
        "conftest telegram group",
        "regal telegram group",
        "snyk code telegram",
        "semgrep telegram group",
        "sonarqube telegram group",
        "codeclimate telegram group",
        "codacy telegram group",
        "lgtm telegram group",
        "codeql telegram group",
        "infer telegram group",
        "flow telegram group",
        "mypy telegram group",
        "pylint telegram group",
        "eslint telegram group",
        "prettier telegram group",
        "black telegram group",
        "ruff telegram group",
        "gofmt telegram group",
        "rustfmt telegram group",
        "shfmt telegram group",
        "beautysh telegram group",
        "uncrustify telegram group",
        "astyle telegram group",
        "clang format telegram",
        "ktlint telegram group",
        "detekt telegram group",
        "spotless telegram group",
        "checkstyle telegram group",
        "pmd telegram group",
        "findbugs telegram group",
        "spotbugs telegram group",
        "error-prone telegram group",
        "archunit telegram group",
        "degraph telegram group",
        "jdepend telegram group",
        "structure101 telegram group",
        "sonargraph telegram group",
        "soto ascii telegram",
        "dependi telegram group",
        "renovate telegram group",
        "dependabot telegram group",
        "socket telegram group",
        "snyk open source telegram",
        "owasp dependency check telegram",
        "cve search telegram group",
        "nvd telegram group",
        "osv telegram group",
        "advisory database telegram",
        "github advisory telegram",
        "gitlab advisory telegram",
        "npm audit telegram group",
        "pip audit telegram group",
        "cargo audit telegram group",
        "bundler audit telegram",
        "gemnasium telegram group",
        "snyk container telegram",
        "trivy container telegram",
        "grype container telegram",
        "clair telegram group",
        "quay telegram group",
        "harbor telegram group",
        "jfrog xray telegram",
        "snyk iac telegram",
        "checkov iac telegram",
        "tfsec iac telegram",
        "kics telegram group",
        "terrascan telegram group",
        "prowler telegram group",
        "scout suite telegram",
        "cloudsploit telegram group",
        "polaris telegram group",
        "kubescape telegram group",
        "kube-bench telegram group",
        "kube-hunter telegram group",
        "kubeaudit telegram group",
        "kubeletctl telegram group",
        "kubeletctl telegram group",
        "kubeletctl telegram group",
        "kubeletctl telegram group",
    ]

    def __init__(
        self,
        name: str = "github",
        config: dict | None = None,
    ) -> None:
        super().__init__(name, config)
        cfg = config or {}
        self.queries = cfg.get("queries", self.SEARCH_QUERIES)
        self.max_results = cfg.get("max_results", 30)
        self.token = os.getenv("GITHUB_TOKEN")
        self._rate_limited_until = 0

    def _get_headers(self) -> dict:
        """Get headers with optional auth."""
        headers = {"Accept": "application/vnd.github.v3+json"}
        if self.token:
            headers["Authorization"] = f"token {self.token}"
        return headers

    async def discover(self) -> list[str]:
        """Discover URLs from GitHub."""
        # Check if rate limited
        if asyncio.get_event_loop().time() < self._rate_limited_until:
            logger.debug("github_rate_limited_skip")
            return []

        all_urls = []

        async with httpx.AsyncClient(
            timeout=30,
            follow_redirects=True,
            headers=self._get_headers(),
        ) as client:
            for query in self.queries:
                try:
                    urls = await self._search_code(client, query)
                    all_urls.extend(urls)
                    # Small delay between queries
                    await asyncio.sleep(2)
                except Exception as e:
                    logger.error("github_search_failed", query=query, error=str(e))

        unique_urls = list(set(all_urls))
        logger.info("github_completed", queries=len(self.queries), found=len(unique_urls))
        return unique_urls

    async def _search_code(self, client: httpx.AsyncClient, query: str) -> list[str]:
        """Search GitHub code for Telegram links."""
        urls = []

        search_url = "https://api.github.com/search/code"
        params = {
            "q": f"{query} in:file extension:md",
            "per_page": min(self.max_results, 100),
        }

        response = await client.get(search_url, params=params)

        if response.status_code == 403:
            # Rate limited - back off for 10 minutes
            self._rate_limited_until = asyncio.get_event_loop().time() + 600
            logger.warning("github_rate_limited", backoff_seconds=600)
            return urls

        if response.status_code == 401:
            logger.warning("github_auth_required")
            return urls

        response.raise_for_status()

        data = response.json()
        items = data.get("items", [])

        for item in items:
            content_url = item.get("url")
            if content_url:
                file_urls = await self._fetch_file_content(client, content_url)
                urls.extend(file_urls)

        return urls

    async def _fetch_file_content(
        self, client: httpx.AsyncClient, url: str
    ) -> list[str]:
        """Fetch file content and extract Telegram links."""
        urls = []

        try:
            response = await client.get(url)
            response.raise_for_status()

            data = response.json()
            content = data.get("content", "")

            if content:
                decoded = base64.b64decode(content).decode("utf-8", errors="ignore")
                telegram_links = extract_telegram_links(decoded)
                urls.extend(telegram_links)

        except Exception as e:
            logger.error("file_fetch_failed", url=url, error=str(e))

        return urls
