"""Telegram search source - uses Telegram's built-in search."""

import asyncio

import structlog
from telethon.errors import FloodWaitError

from app.telegram.client import TelegramClient
from app.telegram.rate_limiter import RateLimiter

from .base_source import BaseSource

logger = structlog.get_logger()


class TelegramSearchSource(BaseSource):
    """Discovers Telegram chats using Telegram's search API."""

    CATEGORIES = [
        "anime", "crypto", "bitcoin", "ethereum", "nft", "defi", "trading",
        "python", "javascript", "typescript", "coding", "programming", "developer",
        "gaming", "games", "esport", "steam",
        "news", "media", "press",
        "business", "startup", "marketing",
        "tech", "technology", "ai", "machine learning",
        "music", "movies", "anime", "manga",
        "sports", "football", "basketball",
        "education", "learning", "course",
        "travel", "tourism", "vacation",
        "food", "cooking", "recipe",
        "health", "fitness", "workout",
        "fashion", "style", "beauty",
        "art", "design", "photo",
        "science", "physics", "chemistry",
        "cars", "auto", "motorsport",
        "jobs", "freelance", "remote work",
        "english", "languages", "spanish",
        "books", "reading", "literature",
        "photography", "camera",
        "linux", "windows", "mac",
        "android", "ios", "mobile",
        "web", "frontend", "backend",
        "database", "sql", "mongodb",
        "devops", "docker", "kubernetes",
        "cybersecurity", "hacking", "infosec",
        "crypto", "blockchain", "web3",
        "realestate", "investing",
        "parenting", "family",
        "pets", "dogs", "cats",
        "gardening", "plants",
        "diy", "crafts", "woodworking",
        "podcast", "youtube",
        "writing", "blogging",
        "yoga", "meditation",
        "philosophy", "psychology",
        "history", "geography",
        "astronomy", "space",
        "mathematics", "statistics",
        "economics", "finance",
        "dating", "relationships",
        "wedding",
        "watches", "jewelry",
        "tech", "gadgets", "reviews",
        "smartphones", "laptops",
        "esports", "streaming",
        "youtube", "content creation",
        "social media", "instagram", "tiktok",
        "dating", "tinder",
        "travel", "backpacking",
        "digital nomad", "remote work",
        "freelancing", "upwork",
        "startup", "entrepreneur",
        "marketing", "growth hacking",
        "seo", "content marketing",
        "email marketing", "newsletter",
        "ecommerce", "shopify",
        "crypto", "defi", "nft",
        "stocks", "investing",
        "realestate", "rental",
        "personal finance", "budgeting",
        "taxes", "accounting",
        "legal", "contracts",
        "health", "wellness",
        "nutrition", "diet",
        "sleep", "biohacking",
        "productivity", "automation",
        "minimalism",
        "sustainability",
        "vegan", "vegetarian",
        "keto", "paleo",
        "running", "marathon",
        "cycling", "swimming",
        "yoga", "pilates",
        "martial arts", "boxing",
        "weightlifting", "calisthenics",
        "hiking", "trekking",
        "camping", "overlanding",
        "fishing", "hunting",
        "cooking", "baking",
        "cocktails", "bartending",
        "coffee", "tea",
        "wine", "beer",
        "chocolate", "pastry",
        "sushi", "ramen",
        "vegan recipes", "healthy recipes",
        "meal prep", "slow cooker",
        "air fryer", "instant pot",
        "gardening", "hydroponics",
        "indoor plants", "bonsai",
        "pets", "dog training",
        "aquarium", "fish keeping",
        "reptiles", "snakes",
        "birds", "parrots",
        "horses", "equestrian",
        "diy", "woodworking",
        "knitting", "sewing",
        "3d printing", "laser cutting",
        "robotics", "electronics",
        "photography", "portrait",
        "videography", "cinematography",
        "youtube", "content creation",
        "podcasting", "audio production",
        "music production", "beat making",
        "guitar", "piano", "drums",
        "singing", "choir",
        "writing", "creative writing",
        "blogging", "copywriting",
        "self improvement", "personal development",
        "productivity", "atomic habits",
        "meditation", "mindfulness",
        "stoicism", "philosophy",
        "languages", "english", "spanish",
        "chinese", "japanese", "korean",
        "german", "italian", "portuguese",
        "history", "ancient history",
        "geography", "culture",
        "astronomy", "astrology",
        "paranormal", "ufos",
        "true crime", "cold cases",
        "comedy", "standup",
        "horror", "thriller",
        "fantasy", "sci-fi",
        "manga", "manhwa",
        "comics", "webtoons",
        "anime", "studio ghibli",
        "cartoons", "animation",
        "movies", "film", "cinema",
        "tv shows", "netflix",
        "documentaries",
        "music", "albums", "concerts",
        "festivals",
        "sports", "nba", "nfl",
        "soccer", "premier league",
        "tennis", "wimbledon",
        "f1", "motogp",
        "mma", "ufc", "boxing",
        "olympics", "world cup",
        "esports", "league of legends",
        "valorant", "fortnite", "minecraft",
        "poker", "casino",
        "chess", "go",
        "board games", "dnd",
        "card games", "magic the gathering",
        "puzzles", "sudoku",
        "magic", "illusions",
        "cosplay", "costumes",
        "tattoos", "piercings",
        "fashion", "streetwear",
        "sneakers", "jordans",
        "watches", "luxury",
        "cars", "supercars",
        "motorcycles", "cycling",
        "aviation", "planes",
        "sailing", "yachts",
        "diving", "scuba",
        "skiing", "snowboarding",
        "surfing", "kitesurfing",
        "rock climbing", "bouldering",
        "hiking", "backpacking",
        "camping", "glamping",
        "overlanding", "van life",
        "digital nomad", "remote work",
        "freelancing", "consulting",
        "entrepreneurship", "startups",
        "marketing", "sales",
        "seo", "social media marketing",
        "email marketing",
        "ecommerce", "shopify",
        "affiliate marketing",
        "investing", "stocks",
        "crypto", "bitcoin",
        "real estate", "rental",
        "personal finance",
        "tax optimization",
        "insurance",
        "retirement",
        "estate planning",
        "education", "online courses",
        "language learning",
        "coding bootcamps",
        "job hunting", "interviews",
        "career growth", "leadership",
        "productivity", "automation",
        "software", "apps",
        "ai tools", "chatgpt",
        "no code", "low code",
        "cybersecurity", "privacy",
        "linux", "ubuntu",
        "windows", "macos",
        "android", "ios",
        "web development", "react",
        "nodejs", "django", "fastapi",
        "databases", "sql",
        "cloud", "aws", "docker",
        "devops", "kubernetes",
        "machine learning", "deep learning",
        "data science", "analytics",
        "robotics", "iot",
        "blockchain", "web3",
        "vr", "ar", "metaverse",
        "quantum computing",
        "space", "nasa", "spacex",
        "climate", "environment",
        "renewable energy", "solar",
        "biotech", "genetics",
        "nanotech", "3d printing",
        "agriculture", "farming",
        "food tech", "vertical farming",
        "health tech", "telemedicine",
        "medtech", "diagnostics",
        "pharma", "drug discovery",
        "edtech", "online learning",
        "fintech", "neobanks",
        "insurtech", "insurance tech",
        "proptech", "real estate tech",
        "legaltech", "contract automation",
        "hrtech", "hr tech",
        "martech", "marketing tech",
        "cleantech", "climate tech",
        "energy tech", "smart grid",
        "water tech", "waste tech",
        "construction tech", "smart buildings",
        "logistics tech", "supply chain",
        "food tech", "agritech",
        "fashion tech", "retail tech",
        "beauty tech", "personalized beauty",
        "sports tech", "fitness tech",
        "entertainment tech", "streaming",
        "social tech", "community platforms",
        "accessibility tech", "assistive tech",
        "elder tech", "senior care",
        "child tech", "edtech",
        "pet tech", "vet tech",
        "legal tech", "compliance tech",
        "audit tech", "accounting tech",
        "hr tech", "recruiting tech",
        "learning tech", "edtech tools",
        "marketing tech", "creative tech",
        "sales tech", "conversation intelligence",
        "customer success tech", "support tech",
        "analytics tech", "data tech",
        "integration tech", "api management",
        "automation tech", "rpa",
        "security tech", "cybersecurity tools",
        "privacy tech", "compliance tools",
        "cloud tech", "infrastructure tools",
        "developer tools", "devtools",
        "monitoring tools", "observability",
        "ci/cd tools", "deployment tools",
        "database tools", "data management",
        "ai tools", "ml tools",
        "creative tools", "design tools",
        "productivity tools", "project management",
        "communication tools", "messaging",
        "file management", "cloud storage",
        "security tools", "password managers",
        "vpn", "privacy tools",
        "crypto tools", "wallets",
        "nft tools", "marketplaces",
        "web3 tools", "dapp development",
        "blockchain analytics",
        "dao tools", "governance",
        "tokenization", "security tokens",
        "decentralized identity",
        "decentralized storage", "ipfs",
        "decentralized compute",
        "decentralized bandwidth",
        "decentralized social",
        "decentralized finance", "aave",
        "decentralized exchange", "dex",
        "yield farming", "liquidity mining",
        "lending protocols",
        "stablecoins", "dai", "usdc",
        "cross-chain", "bridges",
        "layer 2", "rollups",
        "consensus mechanisms",
        "smart contracts", "solidity",
        "dapp development",
        "nft development",
        "token standards", "erc20",
        "dao creation", "governance",
        "treasury management", "multisig",
        "tokenomics", "supply mechanics",
        "token launches", "ido",
        "airdrops", "community incentives",
        "staking mechanisms", "liquid staking",
        "restaking protocols",
        "modular blockchain", "celestia",
        "data availability",
        "shared sequencing",
        "mev", "mev protection",
        "account abstraction",
        "paymasters", "bundlers",
        "wallet connect", "wallet standard",
        "hardware wallets", "ledger",
        "social recovery",
        "soulbound tokens",
        "proof of humanity",
        "sybil resistance",
        "public goods",
        "regenerative finance",
        "carbon credits",
        "biodiversity credits",
        "regenerative agriculture",
        "ocean conservation",
        "reforestation",
        "clean energy",
        "carbon removal",
        "climate adaptation",
        "environmental monitoring",
        "open data", "transparency",
        "civic tech", "govtech",
        "e-governance",
        "participatory democracy",
        "open source",
        "decentralized governance",
        "rage quit", "exit mechanisms",
        "multi-sig", "time locks",
        "bug bounties", "audits",
        "security best practices",
        "incident response",
        "compliance frameworks",
        "data protection",
        "encryption at rest",
        "key management",
        "access control", "rbac",
        "identity management", "sso",
        "api security", "rate limiting",
        "owasp top 10",
        "code review", "static analysis",
        "dependency scanning",
        "container security",
        "cloud security", "cspm",
        "endpoint security", "edr",
        "network security", "firewall",
        "email security", "anti-phishing",
        "web security", "waf",
        "mobile security",
        "iot security",
        "devsecops", "shift left",
        "threat intelligence",
        "forensics", "malware analysis",
        "reverse engineering",
        "vulnerability research",
        "bug bounty",
        "red team", "purple team",
        "security awareness",
        "governance", "risk", "compliance",
        "audit management",
        "data governance",
        "metadata management",
        "data privacy", "consent",
        "data retention",
        "data masking", "anonymization",
        "backup", "recovery",
        "disaster recovery",
        "high availability",
        "load balancing",
        "blue green deployment",
        "feature flags",
        "release management",
        "documentation", "api docs",
        "sdk", "client libraries",
        "testing", "unit tests",
        "test automation", "ci/cd",
        "performance testing",
        "security testing",
        "code quality", "linting",
        "code review",
        "refactoring", "technical debt",
        "design patterns",
        "domain driven design",
        "event sourcing", "cqrs",
        "api design", "rest", "graphql",
        "authentication", "oauth2",
        "jwt", "session management",
        "cors", "csrf",
        "input validation",
        "logging", "structured logging",
        "monitoring", "metrics",
        "observability",
        "profiling", "optimization",
        "caching", "cdn",
        "connection pooling",
        "circuit breaker",
        "graceful degradation",
        "health checks",
        "zero downtime",
        "database", "sql", "nosql",
        "relational", "document",
        "sharding", "partitioning",
        "indexing", "query optimization",
        "transactions", "acid",
        "migration", "schema evolution",
        "orm", "query builder",
        "read replicas",
        "caching", "redis",
        "message queues", "kafka",
        "event streaming",
        "search", "elasticsearch",
        "full text search",
        "geospatial", "postgis",
        "vector databases", "pinecone",
        "embeddings", "semantic search",
        "graph databases", "neo4j",
        "blockchain", "distributed ledger",
        "smart contracts", "dapps",
        "cloud", "aws", "azure",
        "iaas", "paas", "saas",
        "containers", "docker",
        "orchestration", "kubernetes",
        "serverless", "lambda",
        "infrastructure as code",
        "configuration management",
        "ci/cd", "github actions",
        "monitoring", "prometheus",
        "logging", "elk stack",
        "tracing", "jaeger",
        "security", "vault",
        "networking", "vpc",
        "cdn", "cloudfront",
        "storage", "s3",
        "databases", "rds",
        "caching", "elasticache",
        "message queues", "sqs",
        "search", "opensearch",
        "ai/ml", "sagemaker",
        "data analytics", "redshift",
        "etl", "glue",
        "visualization", "looker",
        "devops", "codepipeline",
        "security", "guard duty",
        "compliance", "cloud trail",
        "cost optimization",
        "governance", "organizations",
        "identity", "iam",
        "api management", "api gateway",
        "edge", "cloudfront functions",
        "iot", "iot core",
        "edge computing",
        "quantum", "braket",
        "hybrid cloud", "anthos",
        "multi-cloud",
        "cost management", "finops",
        "sustainability",
        "accessibility", "a11y",
        "internationalization", "i18n",
        "usability", "user research",
        "interaction design",
        "visual design", "ui design",
        "typography", "color theory",
        "responsive design",
        "dark mode", "design tokens",
        "animation", "motion design",
        "illustration", "icons",
        "prototyping", "figma",
        "design systems",
        "branding", "logo design",
        "web design", "landing pages",
        "mobile design", "app design",
        "desktop design",
        "print design", "packaging",
        "motion graphics",
        "3d design", "blender",
        "ar/vr design",
        "game design",
        "ux writing", "microcopy",
        "information design",
        "accessibility", "wcag",
        "inclusive design",
        "cognitive load",
        "feedback loops",
        "wayfinding", "navigation",
        "user flows", "task analysis",
        "personas", "empathy maps",
        "a/b testing",
        "eye tracking", "heat maps",
        "surveys", "interviews",
        "analytics", "funnels",
        "retention", "engagement",
        "nps", "csat",
        "keyboard navigation",
        "color contrast",
        "error messages", "form design",
        "onboarding", "tutorials",
        "gamification", "rewards",
        "personalization",
        "social features",
        "notifications", "alerts",
        "offline support",
        "performance", "lazy loading",
        "seo", "meta tags",
        "tracking", "attribution",
        "privacy", "consent",
        "authentication",
        "testing", "jest",
        "linting", "eslint",
        "formatting", "prettier",
        "static analysis", "mypy",
        "dependency management",
        "virtual environments",
        "package registries",
        "documentation", "sphinx",
        "api documentation",
        "monitoring", "grafana",
        "logging", "loki",
        "tracing", "opentelemetry",
        "profiling",
        "debugging",
        "optimization",
        "compression", "minification",
        "cdn", "edge caching",
        "serverless", "edge functions",
        "containers", "docker",
        "orchestration", "kubernetes",
        "infrastructure", "terraform",
        "security", "snyk",
        "compliance", "soc2",
        "monitoring", "uptime",
        "alerting", "pagerduty",
        "incident management",
        "sre", "slis",
        "capacity planning",
        "disaster recovery",
        "business continuity",
        "cost optimization",
        "sustainability",
        "developer experience",
        "documentation",
        "code review",
        "knowledge sharing",
        "mentoring", "coaching",
        "culture", "values",
        "hiring", "interviewing",
        "retention", "engagement",
        "diversity", "inclusion",
        "remote work",
        "work life balance",
        "continuous learning",
        "innovation",
        "collaboration",
        "ownership",
        "transparency",
        "respect", "empathy",
        "quality", "craftsmanship",
        "impact", "outcomes",
        "sustainability",
        "simplicity", "clarity",
        "performance", "efficiency",
        "security", "reliability",
        "scalability",
        "usability", "accessibility",
        "observability",
        "automation",
        "documentation",
        "tools", "processes",
        "standards", "conventions",
        "patterns", "principles",
        "tradeoffs", "decisions",
        "context", "constraints",
        "risks", "opportunities",
        "strengths", "weaknesses",
        "research", "discovery",
        "ideation", "brainstorming",
        "prototyping", "testing",
        "iteration", "feedback",
        "documentation",
        "collaboration",
        "execution", "delivery",
        "monitoring", "measuring",
        "optimizing", "improving",
        "maintenance", "support",
        "deprecation", "migration",
        "archiving", "cleanup",
        "security", "compliance",
        "audit", "review",
        "planning", "estimation",
        "risk management",
        "stakeholder management",
        "budget", "resources",
        "timeline", "milestones",
        "quality assurance",
        "release management",
        "monitoring", "alerting",
        "postmortems",
        "documentation",
        "training", "onboarding",
        "community", "open source",
        "partnerships",
        "innovation", "research",
        "strategy", "vision",
        "prioritization",
        "execution", "delivery",
        "feedback", "iteration",
        "learning", "growth",
        "sustainability",
        "impact", "value",
        "success", "metrics",
        "goals", "objectives",
        "okr", "kpi",
        "data driven",
        "continuous improvement",
        "blameless",
        "innovation culture",
        "customer focus",
        "agile", "lean",
        "collaborative",
        "transparent",
        "inclusive",
        "empowered", "trusted",
        "quality focused",
        "impact driven",
        "sustainable", "maintainable",
        "resilient", "reliable",
        "scalable", "performant",
        "secure", "compliant",
        "observable", "debuggable",
        "automated", "reproducible",
        "documented", "communicated",
        "measured", "analyzed",
        "learned", "improved",
        # Russian categories
        "программирование", "разработка", "кодинг",
        "игры", "гейминг", "киберспорт",
        "новости", "медиа", "пресса",
        "бизнес", "стартап", "маркетинг",
        "технологии", "айти",
        "музыка", "фильмы", "аниме",
        "спорт", "футбол",
        "образование", "обучение",
        "путешествия", "туризм",
        "еда", "кулинария",
        "здоровье", "фитнес",
        "мода", "стиль",
        "искусство", "дизайн",
        "наука", "физика",
        "автомобили", "авто",
        "вакансии", "фриланс",
        "английский", "языки",
        "книги", "чтение",
        "linux", "windows",
        "android", "ios",
        "веб", "фронтенд",
        "базы данных", "sql",
        "девопс", "docker",
        "крипто", "трейдинг",
        "инвестиции", "акции",
        "недвижимость", "аренда",
        "юриспруденция",
        "медицина", "врач",
        "ветеринария",
        "архитектура", "интерьер",
        "авиация", "дрон",
        "охота", "рыбалка",
        "астрономия", "космос",
        "геология",
        "математика", "статистика",
        "экономика", "финансы",
        "психология", "философия",
        "политика",
        "религия", "медитация",
        "йога", "пилатес",
        "боевые искусства",
        "сёрфинг", "лыжи",
        "гольф", "теннис",
        "шахматы", "настолки",
        "фокусы",
        "юмор", "мемы",
        "знакомства", "отношения",
        "свадьба",
        "мода", "кроссовки",
        "техника", "гаджеты",
        "смартфоны", "ноутбуки",
        "игры", "стриминг",
        "ютуб", "контент",
        "соцсети", "инстаграм",
        "знакомства", "тиндер",
        "путешествия", "бэкпекинг",
        "цифровой кочевник",
        "фриланс", "апворк",
        "стартап", "предприниматель",
        "маркетинг", "реклама",
        "seo", "контент-маркетинг",
        "email маркетинг",
        "электронная коммерция",
        "крипто", "дефи",
        "акции", "инвестиции",
        "недвижимость",
        "личные финансы",
        "налоги", "бухгалтерия",
        "юриспруденция",
        "здоровье", "ментальное здоровье",
        "нутрициология", "диета",
        "сон", "биохакинг",
        "продуктивность",
        "минимализм",
        "устойчивое развитие",
        "веганство",
        "кето", "палео",
        "бег", "марафон",
        "велоспорт",
        "плавание", "триатлон",
        "йога", "виньяса",
        "пилатес", "танцы",
        "боевые искусства", "бокс",
        "силовые тренировки",
        "калистеника", "паркур",
        "походы", "треккинг",
        "кемпинг", "оверлендинг",
        "рыбалка",
        "охота",
        "кулинария", "выпечка",
        "гриль", "барбекю",
        "коктейли",
        "кофе", "чай",
        "вино", "пиво",
        "шоколад", "десерты",
        "суши", "рамен",
        "веганские рецепты",
        "meal prep",
        "садоводство",
        "комнатные растения",
        "цветы",
        "питомцы", "дрессировка",
        "аквариум",
        "рептилии",
        "птицы",
        "лошади",
        "диай", "столярка",
        "вязание", "шитье",
        "3д печать",
        "робототехника", "ардуино",
        "фотография", "портрет",
        "видеография",
        "ютуб", "монтаж видео",
        "подкастинг",
        "музыкальное производство",
        "диджей", "мастеринг",
        "гитара", "фортепиано",
        "вокал",
        "писательство",
        "блогинг", "копирайтинг",
        "саморазвитие",
        "продуктивность",
        "медитация", "осознанность",
        "стоицизм", "философия",
        "языки", "английский",
        "китайский", "японский",
        "немецкий", "итальянский",
        "история",
        "география",
        "астрономия",
        "паранормальное",
        "настоящая преступность",
        "юмор", "стендап",
        "хоррор", "триллер",
        "фэнтези", "фантастика",
        "манга",
        "комиксы", "вебтуны",
        "аниме",
        "мультфильмы",
        "кино", "фильм",
        "сериалы", "нетфликс",
        "документалки",
        "музыка", "концерты",
        "фестивали",
        "спорт", "нба",
        "футбол", "премьер-лига",
        "теннис",
        "формула 1",
        "ммА", "уфс",
        "олимпиада",
        "киберспорт", "лига легенд",
        "покер", "казино",
        "шахматы", "го",
        "настолки", "рпг",
        "карточные игры",
        "головоломки",
        "фокусы",
        "косплей",
        "татуировки",
        "мода", "винтаж",
        "кроссовки",
        "часы", "ролекс",
        "автомобили", "суперкары",
        "мотоциклы",
        "aviation", "самолёты",
        "парусный спорт",
        "дайвинг", "скалолазание",
        "лыжи", "сноуборд",
        "сёрфинг",
        "скалолазание",
        "походы",
        "кемпинг", "глэмпинг",
        "оверлендинг",
        "цифровой кочевник",
        "фриланс", "консалтинг",
        "предпринимательство",
        "маркетинг", "продажи",
        "seo",
        "электронная коммерция",
        "инвестиции", "акции",
        "крипто", "биткоин",
        "недвижимость",
        "личные финансы",
        "оптимизация налогов",
        "юриспруденция",
        "страхование",
        "пенсия",
        "планирование наследства",
        "образование", "онлайн курсы",
        "изучение языков",
        "кодинг курсы",
        "поиск работы",
        "карьерный рост",
        "продуктивность",
        "ии инструменты", "чатгпт",
        "no code", "low code",
        "кибербезопасность", "vpn",
        "linux", "убунту",
        "windows", "мак ос",
        "android", "ios",
        "веб разработка", "реакт",
        "ноджс", "джанго",
        "базы данных", "sql",
        "облака", "aws",
        "девопс", "кубернетес",
        "машинное обучение",
        "дата сайенс",
        "робототехника",
        "блокчейн", "веб3",
        "вр", "ар",
        "квантовые вычисления",
        "космос", "nasa",
        "климат",
        "возобновляемая энергия",
        "биотехнологии",
        "нанотехнологии",
        "сельское хозяйство",
        "foodtech",
        "healthtech",
        "телемедицина",
        "медтех",
        "фарма",
        "edtech",
        "финтерм",
        "инститек",
        "проптех",
        "легалтек",
        "hrtech",
        "маркетинг технологии",
        "cleantech",
        "энергетические технологии",
        "водные технологии",
        "construction tech",
        "логистические технологии",
        "agritech",
        "fashion tech",
        "beauty tech",
        "sports tech",
        "entertainment tech",
        "social tech",
        "accessibility tech",
        "elder tech",
        "child tech",
        "pet tech",
        "legal tech",
        "audit tech",
        "hr tech",
        "learning tech",
        "marketing tech",
        "sales tech",
        "customer success tech",
        "analytics tech",
        "integration tech",
        "automation tech",
        "security tech",
        "privacy tech",
        "cloud tech",
        "developer tools",
        "monitoring tools",
        "ci/cd tools",
        "database tools",
        "ai tools",
        "creative tools",
        "productivity tools",
        "communication tools",
        "file management",
        "security tools",
        "vpn",
        "crypto tools",
        "nft tools",
        "web3 tools",
        "blockchain analytics",
        "dao tools",
        "tokenization",
        "decentralized identity",
        "decentralized storage",
        "decentralized compute",
        "decentralized bandwidth",
        "decentralized social",
        "decentralized finance",
        "decentralized exchange",
        "yield farming",
        "lending protocols",
        "stablecoins",
        "cross-chain",
        "layer 2",
        "consensus mechanisms",
        "smart contracts",
        "dapp development",
        "nft development",
        "token standards",
        "dao creation",
        "treasury management",
        "tokenomics",
        "token launches",
        "airdrops",
        "staking mechanisms",
        "restaking protocols",
        "modular blockchain",
        "data availability",
        "shared sequencing",
        "mev",
        "account abstraction",
        "paymasters",
        "wallet connect",
        "hardware wallets",
        "social recovery",
        "soulbound tokens",
        "proof of humanity",
        "sybil resistance",
        "public goods",
        "regenerative finance",
        "carbon credits",
        "biodiversity credits",
        "regenerative agriculture",
        "ocean conservation",
        "reforestation",
        "clean energy",
        "carbon removal",
        "climate adaptation",
        "environmental monitoring",
        "open data",
        "civic tech",
        "e-governance",
        "participatory democracy",
        "open source",
        "decentralized governance",
        "multi-sig",
        "bug bounties",
        "security best practices",
        "incident response",
        "compliance frameworks",
        "data protection",
        "encryption at rest",
        "key management",
        "access control",
        "identity management",
        "api security",
        "owasp top 10",
        "code review",
        "dependency scanning",
        "container security",
        "cloud security",
        "endpoint security",
        "network security",
        "email security",
        "web security",
        "mobile security",
        "iot security",
        "devsecops",
        "threat intelligence",
        "forensics",
        "reverse engineering",
        "vulnerability research",
        "bug bounty",
        "red team",
        "security awareness",
        "governance",
        "audit management",
        "data governance",
        "metadata management",
        "data privacy",
        "data retention",
        "data masking",
        "backup",
        "disaster recovery",
        "high availability",
        "load balancing",
        "blue green deployment",
        "feature flags",
        "release management",
        "documentation",
        "sdk",
        "testing",
        "test automation",
        "performance testing",
        "security testing",
        "code quality",
        "refactoring",
        "design patterns",
        "domain driven design",
        "event sourcing",
        "api design",
        "authentication",
        "jwt",
        "cors",
        "input validation",
        "logging",
        "monitoring",
        "observability",
        "profiling",
        "caching",
        "connection pooling",
        "circuit breaker",
        "health checks",
        "database",
        "sql",
        "sharding",
        "indexing",
        "transactions",
        "migration",
        "orm",
        "read replicas",
        "redis",
        "message queues",
        "event streaming",
        "search",
        "vector databases",
        "embeddings",
        "graph databases",
        "blockchain",
        "cloud",
        "containers",
        "orchestration",
        "serverless",
        "infrastructure as code",
        "ci/cd",
        "monitoring",
        "logging",
        "tracing",
        "security",
        "networking",
        "cdn",
        "storage",
        "databases",
        "caching",
        "ai/ml",
        "data analytics",
        "etl",
        "visualization",
        "devops",
        "compliance",
        "cost optimization",
        "governance",
        "identity",
        "api management",
        "edge",
        "iot",
        "quantum",
        "hybrid cloud",
        "multi-cloud",
        "finops",
        "sustainability",
        "accessibility",
        "internationalization",
        "usability",
        "interaction design",
        "visual design",
        "typography",
        "responsive design",
        "animation",
        "illustration",
        "prototyping",
        "design systems",
        "branding",
        "web design",
        "mobile design",
        "print design",
        "motion graphics",
        "3d design",
        "ar/vr design",
        "game design",
        "ux writing",
        "information design",
        "inclusive design",
        "feedback loops",
        "wayfinding",
        "user flows",
        "personas",
        "a/b testing",
        "surveys",
        "analytics",
        "retention",
        "nps",
        "error messages",
        "onboarding",
        "gamification",
        "personalization",
        "notifications",
        "performance",
        "seo",
        "tracking",
        "privacy",
        "testing",
        "linting",
        "formatting",
        "static analysis",
        "dependency management",
        "documentation",
        "api documentation",
        "profiling",
        "debugging",
        "optimization",
        "compression",
        "cdn",
        "serverless",
        "containers",
        "infrastructure",
        "security",
        "compliance",
        "monitoring",
        "alerting",
        "incident management",
        "sre",
        "capacity planning",
        "disaster recovery",
        "cost optimization",
        "developer experience",
        "documentation",
        "code review",
        "knowledge sharing",
        "mentoring",
        "culture",
        "hiring",
        "retention",
        "diversity",
        "remote work",
        "work life balance",
        "continuous learning",
        "innovation",
        "collaboration",
        "ownership",
        "transparency",
        "quality",
        "impact",
        "sustainability",
        "simplicity",
        "performance",
        "security",
        "scalability",
        "usability",
        "observability",
        "automation",
        "documentation",
        "tools",
        "standards",
        "patterns",
        "tradeoffs",
        "context",
        "risks",
        "strengths",
        "research",
        "ideation",
        "prototyping",
        "iteration",
        "documentation",
        "execution",
        "monitoring",
        "optimization",
        "maintenance",
        "deprecation",
        "archiving",
        "security",
        "audit",
        "planning",
        "risk management",
        "stakeholder management",
        "budget",
        "timeline",
        "quality assurance",
        "release management",
        "postmortems",
        "training",
        "community",
        "partnerships",
        "innovation",
        "strategy",
        "prioritization",
        "execution",
        "feedback",
        "learning",
        "sustainability",
        "impact",
        "success",
        "goals",
        "okr",
        "data driven",
        "continuous improvement",
        "innovation culture",
        "customer focus",
        "agile",
        "collaborative",
        "transparent",
        "inclusive",
        "empowered",
        "quality focused",
        "impact driven",
        "sustainable",
        "resilient",
        "scalable",
        "secure",
        "observable",
        "automated",
        "documented",
        "measured",
        "learned",
    ]

    def __init__(
        self,
        name: str = "telegram_search",
        config: dict | None = None,
    ) -> None:
        super().__init__(name, config)
        cfg = config or {}
        self.categories = cfg.get("categories", self.CATEGORIES)
        self.max_per_category = cfg.get("max_per_category", 20)
        self._client: TelegramClient | None = None
        self._rate_limiter: RateLimiter | None = None

    async def discover(self) -> list[str]:
        """Discover Telegram chats using search."""
        if self._client is None:
            self._client = TelegramClient()
        if self._rate_limiter is None:
            self._rate_limiter = RateLimiter()

        all_usernames = []

        for category in self.categories:
            try:
                usernames = await self._search_category(category)
                all_usernames.extend(usernames)
                logger.debug("category_searched", category=category, found=len(usernames))
            except FloodWaitError as e:
                logger.warning("flood_wait_category", category=category, seconds=e.seconds)
                await asyncio.sleep(e.seconds)
            except Exception as e:
                logger.debug("category_failed", category=category, error=str(e))

            await asyncio.sleep(0.5)

        urls = [f"https://t.me/{username}" for username in all_usernames if username]
        unique_urls = list(set(urls))

        logger.info("telegram_search_completed", categories=len(self.categories), found=len(unique_urls))
        return unique_urls

    async def _search_category(self, category: str) -> list[str]:
        """Search for chats in a category."""
        usernames = []

        await self._rate_limiter.acquire()
        await self._client.connect()

        if not self._client._authorized:
            return []

        # Search for "{category} chat"
        query = f"{category} chat"
        try:
            result = await self._client.search_entities(query, limit=self.max_per_category)
            for entity in result:
                username = getattr(entity, "username", None)
                if username:
                    usernames.append(username)
        except FloodWaitError:
            raise
        except Exception as e:
            logger.debug("search_error", query=query, error=str(e))

        # Also search for "{category} канал" (Russian)
        query_ru = f"{category} канал"
        try:
            await self._rate_limiter.acquire()
            result = await self._client.search_entities(query_ru, limit=self.max_per_category)
            for entity in result:
                username = getattr(entity, "username", None)
                if username:
                    usernames.append(username)
        except FloodWaitError:
            raise
        except Exception as e:
            logger.debug("search_error", query=query_ru, error=str(e))

        return list(set(usernames))
